version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3316:3306'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql


  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' #-e production
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    extra_hosts:
      - "example.com:127.0.0.1"
      - "baukis.example.com:127.0.0.1"
    environment:
      - SECRET_KEY_BASE=$SECRET_KEY_BASE